config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users
  root to: 'questions#index'

  resources :files, only: %i[destroy]
  resources :links, only: %i[destroy]
  resources :badges, only: %i[ index ]

  concern :votable do
    member do
      post :like
      post :dislike
      delete :cancel_vote
    end
  end

  concern :commentable do
    member do
      post :comment
    end
  end

  resources :questions, concerns: [:votable, :commentable] do
    resources :answers, concerns: [:votable, :commentable], shallow: true, except: %i[show index] do
      member do
        patch :best
      end
    end

    member do
      post :subscribe
      delete :unsubscribe
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, except: %i[new edit] do
        resources :answers, except: %i[new edit], shallow: true
      end
    end
  end

  mount ActionCable.server => '/cable'
end

app/models/question.rb
class Question < ApplicationRecord
  include Votable
  include Commentable

  has_many :answers, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable
  has_one :badge, dependent: :destroy
  has_many :subscribtions, dependent: :destroy
  belongs_to :user

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank
  accepts_nested_attributes_for :badge, reject_if: :all_blank

  validates :title, presence: true
  validates :body, presence: true

  after_create :subscribe_author

  def best_answer
    answers.find_by(best: true)
  end

  def give_badge
    if !best_answer&.user.already_achived?(self.badge)
      best_answer.user.badges << self.badge
    end
  end

  private

  def subscribe_author
    user.subscribtions.build(question: self).save
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted
  include Commented

  before_action :load_question, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]

  after_action :publish_question, only: %i[create]

  authorize_resource

  def index
    @questions = Question.all
  end

  def new
    @question = Question.new()
    @question.links.build
    @question.build_badge
  end

  def create
    @question = current_user.questions.build(question_params)

    if @question.save
      redirect_to @question, notice: 'Your question successfully created.'
    else
      render :new
    end
  end

  def update
    @question.update(question_params)
  end

  def destroy
    @question.destroy
    redirect_to questions_path, notice: 'Question successfully deleted!'
  end

  def show
    @answer = Answer.new()
    @answer.links.build
  end

  private

  def load_question
    @question = Question.with_attached_files.find(params[:id])

    gon.question_id = @question.id
  end

  def question_params
    params.require(:question).permit(:title, :body,
                                      files: [], links_attributes: [:name, :url, :_destroy],
                                      badge_attributes: [:title, :image])
  end

  def publish_question
    return if @question.errors.any?
    ActionCable.server.broadcast(
      'questions',
      ApplicationController.render(
        partial: 'questions/question',
        locals: { question: @question,
                  current_user: current_user
                }
      )
    )
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.slim
= render 'shared/errors', resource: @question
= form_with model: @question, local: true do |f|
  p
    = f.label :title
    = f.text_field :title
  p
    = f.label :body
    = f.text_area :body
  p
    = f.label :files
    = f.file_field :files, multiple: true
  p
    = render 'links/link_form', f: f
  .badge
    = f.fields_for :badge do |b|
      p
        = b.label :title, 'Badge name'
        = b.text_field :title
      p
        = b.label :image
        = b.file_field :image

  p= f.submit 'Ask'

app/views/questions/_question.html.slim
div
  h3= question.title
  p= question.body

  .badge
    p Badge for best answer:
    -if question.badge
      = render question.badge

  .files
    = render 'files/file', resource: question, current_user: current_user

  .links
    = render 'links/link', resource: question, current_user: current_user

  .comments id=question.id
    = render question.comments

  .comment-errors id=question.id

  = render 'comments/form', commentable: question

= form_with model: question, local: false, class: 'hidden', html: { id: "edit-question-#{question.id}" } do |f|
  p
    = f.label :title, 'Your question title'
    = f.text_field :title
  p
    = f.label :body, 'Your question body'
    = f.text_area :body
  p
    = f.label :files
    = f.file_field :files, multiple: true, direct_upload: true
  p
    = render 'links/link_form', f: f

  p= f.submit 'Save'

app/views/questions/comment.js.erb
<% if @comment.persisted? %>
  $('#' + <%= @comment.commentable_id %> + ".comments").append('<%= j render @comment %>');
  $('.new-comment #comment-body' + <%= @comment.commentable_id %>).val('');
<% end %>

app/views/questions/index.html.slim
- if can?(:create, Question)
  p= link_to 'Ask question', new_question_path

.questions
  = render @questions

app/views/questions/new.html.slim
= render 'form'

app/views/questions/show.html.slim
.question
  - if can?(:destroy, @question)
    p= link_to "Delete your question",
      question_path(@question),
      method: "delete"

  - if can?(:update, @question)
    p= link_to 'Edit',
      '#',
      class: 'edit-question-link',
      data: { question_id: @question.id }

  .subscribtions-links
    - if can?(:create, Subscribtion) && can?(:destroy, Subscribtion)
      = render 'subscribtions/subscribtion_links', question: @question

  .question-errors
    = render 'shared/errors', resource: @question

  = render @question

= render 'votes/vote', votable: @question

.best-answer
  - if @question.best_answer
    = render 'answers/best_answer'

div
  h2 All answers:

.answers
  = render @question.answers

- if can?(:create, Answer)
  .answer-errors
      = render 'shared/errors', resource: @answer
  = form_with model: [@question, @answer], local: false, class: "new-answer" do |f|
    p= f.label :body
    p= f.text_area :body
    p= f.label :files
    p= f.file_field :files, multiple: true
    p= render 'links/link_form', f: f
    p= f.submit 'Answer'

app/views/questions/update.js.erb
$('.question-errors').html('<%= render 'shared/errors', resource: @question %>');

<% if !@question.errors.present? %>
  $('.question').html('<%= j render @question %>');
<% end %>