config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users
  root to: 'questions#index'

  resources :files, only: %i[destroy]
  resources :links, only: %i[destroy]
  resources :badges, only: %i[ index ]

  concern :votable do
    member do
      post :like
      post :dislike
      delete :cancel_vote
    end
  end

  concern :commentable do
    member do
      post :comment
    end
  end

  resources :questions, concerns: [:votable, :commentable] do
    resources :answers, concerns: [:votable, :commentable], shallow: true, except: %i[show index] do
      member do
        patch :best
      end
    end

    member do
      post :subscribe
      delete :unsubscribe
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, except: %i[new edit] do
        resources :answers, except: %i[new edit], shallow: true
      end
    end
  end

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :question
  belongs_to :user
  has_many :links, dependent: :destroy, as: :linkable

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank

  validates :body, presence: true

  after_create :send_notification

  def set_best
    if self.question.best_answer
      self.question.best_answer.update(best: false)
      self.update(best: true)
    else
      self.update(best: true)
    end
  end

  private

  def send_notification
    QuestionSubscribtionJob.new.perform(question)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted
  include Commented

  before_action :authenticate_user!
  before_action :load_question, only: %i[create]
  before_action :load_answer, only: %i[destroy update best]

  after_action :publish_answer, only: %i[create]

  authorize_resource

  def create
    @answer = @question.answers.create(answer_params)
    current_user.answers << @answer
  end

  def destroy
    @answer.destroy
  end

  def update
    @answer.update(answer_params)
    @question = @answer.question
  end

  def best
    @question = @answer.question
    @answer.set_best
    @question.give_badge if @question.badge
  end

  private

  def load_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end

  def load_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: [:name, :url, :_destroy])
  end

  def publish_answer
    return if @answer.errors.any?
    ActionCable.server.broadcast(
      "answers_#{@answer.question.id}",
      author_id: @answer.user.id,
      page: render_answer
      )
  end

  def render_answer
    ApplicationController.render(
      partial: 'answers/answer_for_channel',
      locals: {
        answer: @answer,
      }
    )
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
div id=answer.id

  = answer.body

  .answer-files
    = render 'files/file', resource: answer

  .answer-links
    = render 'links/link', resource: answer

  = render 'votes/vote', votable: answer

  .comments id=answer.id
    = render answer.comments

  .comment-errors id=answer.id

  = render 'comments/form', commentable: answer

  - if can?(:destroy, answer)
    p= link_to 'Delete your answer', answer_path(answer), remote: true, method: :delete
    p= link_to 'Edit', '#', class: 'edit-answer-link', data: { answer_id: answer.id }

  - if can?(:best, answer)
    p= button_to('Best', best_answer_path(answer), remote: true, method: :patch)

  - if can?(:updage, answer)
    = form_with model: answer, local: false, class: 'hidden', html: { id: "edit-answer-#{answer.id}" } do |f|
      p
        = f.label :body, 'Your answer'
        = f.text_area :body
      p
        = f.label :files
        = f.file_field :files, multiple: true, direct_upload: true
      p
        = render 'links/link_form', f: f
        p= f.submit 'Save'

app/views/answers/_answer_for_channel.html.slim
div id=answer.id

  = answer.body

.score
  = answer.score

.answer-files
  - if answer.files.attached?
    - answer.files.each do |file|
      div id=file.id
        p= link_to file.filename.to_s, url_for(file)

.answer-links

  - if answer.links.exists?
    .links
      p Links:

      - answer.links.each do |link|
        div id=link.id
          - if link.url =~ /gist.github.com/
            script src="#{link.url}.js"
          - else
            li= link_to link.name, link.url

app/views/answers/_best_answer.html.slim
div
  h2 Best Answer:
  = @question.best_answer.body

app/views/answers/best.js.erb
$('.best-answer').html('<%= j render 'best_answer' %>');

app/views/answers/comment.js.erb
<% if @comment.persisted? %>
  $('#' + <%= @comment.commentable_id %> + ".comments").append('<%= j render @comment %>');
  $('.new-comment #comment-body' + <%= @comment.commentable.id %>).val('');
<% end %>

app/views/answers/create.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% if @answer.persisted? %>
  $('.answers').append('<%= j render @answer %>');
  $('.new-answer #answer_body').val('');
<% end %>

app/views/answers/destroy.js.erb
$('#' + <%= j @answer.id %>).remove()

app/views/answers/update.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% if !@answer.errors.present? %>
  $('.answers').html('<%= j render @question.answers %>');
<% end %>