config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users
  root to: 'questions#index'

  resources :files, only: %i[destroy]
  resources :links, only: %i[destroy]
  resources :badges, only: %i[ index ]

  concern :votable do
    member do
      post :like
      post :dislike
      delete :cancel_vote
    end
  end

  concern :commentable do
    member do
      post :comment
    end
  end

  resources :questions, concerns: [:votable, :commentable] do
    resources :answers, concerns: [:votable, :commentable], shallow: true, except: %i[show index] do
      member do
        patch :best
      end
    end

    member do
      post :subscribe
      delete :unsubscribe
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, except: %i[new edit] do
        resources :answers, except: %i[new edit], shallow: true
      end
    end
  end

  mount ActionCable.server => '/cable'
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :linkable, polymorphic: true

  validates :name, :url, presence: true

  validates_format_of :url, with: URI::regexp(%w[http https])
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :authenticate_user!

  def destroy
    @link = Link.find(params[:id])
    authorize! :destroy, @link
    @link.destroy
  end
end

app/views/links/_link.html.slim
- if resource.links.exists?
  .links
    p Links:

    - resource.links.each do |link|
      div id=link.id
        - if link.url =~ /gist.github.com/
          script src="#{link.url}.js"
        - else
          li= link_to link.name, link.url
        - if can?(:destroy, link)
          = link_to "Delete", link_url(link), method: :delete, remote: true

app/views/links/_link_fields.html.slim
.nested-fields
  .field
    = f.label :name, 'Link name'
    = f.text_field :name
  .field
    = f.label :url
    = f.text_field :url
  = link_to_remove_association "remove task", f

app/views/links/_link_form.html.slim
p Links:
p
= f.fields_for :links do |link|
  = render 'links/link_fields', f: link
.links
  = link_to_add_association 'add link', f, :links, partial: 'links/link_fields'

app/views/links/destroy.js.erb
$('#' + <%= j @link.id %>).remove()